* Models
** Ising model
Named  after  Ernst   Ising,  the  Ising  model  is  a   mathematical  model  of
ferromagnetism.  It consists  of  a  set of  binary  distributed variables  that
follows the Gibbs  distribution. Each variable updates  through nearest neighbor
interactions where for ferromagnetic systems the lowest energy state is achieved
by aligning the spin state with its neighbors.

One of the major properties of the Ising model is the phase transition in two or
more dimensions, i.e.  as a function of noise (temperature)  the model goes from
an ordered phase, to an unordered phase.

It has bee shown  that the Ising model falls within  the same universality class
as (directed)  difussion, and it has  been extended it many  different fields in
cluding studying neural behavior, voter dynamics and so on.

** Potts model
The q-Potts model generalizes the Ising model.  In the Potts model the spins are
not binary but can take on arbitrary spin directions i.e.


.. math:
\theta = \frac{q_i 2 \pi}{q}


$q_i \in n = \{0, \dots, q -  1\}$. In the limit $q \rightarrow \infty$ this model
reduces to the  XY model. One particular interesting extensions  is the cellular
Potts  model  used   to  model  static  and  kinetic   phenomena  in  biological
morphogenesis.

** Bornholdt model
Is an  extensions of the  traditional Ising  model used for  modeling financial
systems. It adds a  global cost term such that each  variable "feels" the effect
of the entire  system. This causes "shocks"  in the system similar  to an abrupt
financial crisis. Each  variable can be given a strategy  that either aligns, or
skews it states  according to this general magnetization. This  causes a dynamic
between traders (variables) that either want to  be apart of the minority or the
majority state.
** AB voter model
** SIRS
Susceptible Infected Recovered (Susceptible) or SIRS model inspired by Youssef &
Scolio (2011) The article describes an individual approach to SIR modeling which
canonically uses a mean-field  approximation. In mean-field approximations nodes
are  assumed to  have  'homogeneous mixing',  i.e.  a node  is  able to  receive
information  from the  entire network.  The individual  approach emphasizes  the
importance of local connectivity motifs in spreading dynamics of any process.

